# Generated by Django 5.1.1 on 2024-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TratadosI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(choices=[('Ley', 'Ley'), ('Decreto Ley', 'Decreto Ley'), ('Reglamento', 'Reglamento'), ('Resolución', 'Resolución'), ('Acuerdo', 'Acuerdo'), ('Norma', 'Norma'), ('Estatuto', 'Estatuto')])),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoría')),
                ('organismo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Organismo Internacional')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fecha de emisión')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/documentos')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('concepto', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Categoría Conceptual')),
            ],
            options={
                'verbose_name': 'tratado',
                'verbose_name_plural': 'tratados',
                'db_table': 'tratado',
            },
        ),
    ]
