# Generated by Django 5.1.1 on 2024-11-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0003_alter_tipologia_nombre_alter_tipologia_sigla'),
        ('Tratados', '0002_tratadosi_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratadosi',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.tipologia'),
        ),
    ]
