# Generated by Django 5.1.1 on 2024-11-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tratados', '0003_alter_tratadosi_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratadosi',
            name='enlace',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Enlace'),
        ),
    ]
