# Generated by Django 5.1.1 on 2024-10-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')])),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoría')),
                ('imagen', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foto')),
                ('entidad', models.CharField(blank=True, max_length=500, null=True, verbose_name='Entidad Responsable')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='Región')),
                ('fuente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Año')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('descriptor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptores')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.municipio')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.provincia')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
