# Generated by Django 5.1.1 on 2024-11-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descriptor',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descriptores'),
        ),
    ]
