# Generated by Django 5.1.1 on 2024-11-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_alter_proyectos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
