# Generated by Django 5.1.1 on 2024-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('tipologia', models.CharField(choices=[('Académica', 'Académica'), ('Científica', 'Científica'), ('Sociedad civil', 'Sociedad civil'), ('ONG', 'ONG'), ('Red', 'Red'), ('Otros', 'Otros')])),
                ('afiliacion', models.CharField(choices=[('Institucional', 'Institucional'), ('Universidad', 'Universidad'), ('ONG', 'ONG')])),
                ('cobertura', models.CharField(choices=[('País', 'País'), ('Provincial', 'Provincial'), ('Municipal', 'Municipal'), ('Empresa', 'Empresa'), ('Región', 'Región')])),
                ('categoria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoría')),
                ('tematica', models.CharField(blank=True, max_length=500, null=True, verbose_name='Temática')),
                ('coordinador', models.CharField(blank=True, max_length=500, null=True, verbose_name='Coordinador')),
                ('fuente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'comunidad',
                'verbose_name_plural': 'comunidades',
                'db_table': 'comunidad',
            },
        ),
    ]
