# Generated by Django 5.1.1 on 2024-11-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0001_initial'),
        ('Nomencladores', '0002_afiliacion_cobertura_comunidadesacademicas_tematica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidades',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='comunidades',
            name='comunid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.comunidadesacademicas'),
        ),
        migrations.AlterField(
            model_name='comunidades',
            name='afiliacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.afiliacion'),
        ),
        migrations.AlterField(
            model_name='comunidades',
            name='cobertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.cobertura'),
        ),
        migrations.AlterField(
            model_name='comunidades',
            name='fuente',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
    ]
