# Generated by Django 5.1.1 on 2024-12-05 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0002_remove_comunidades_tipologia_comunidades_comunid_and_more'),
        ('Nomencladores', '0006_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidades',
            name='comunid',
        ),
        migrations.AddField(
            model_name='comunidades',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.tipologia'),
        ),
    ]
