# Generated by Django 5.1.1 on 2024-12-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0003_remove_comunidades_comunid_comunidades_tipologia'),
        ('Nomencladores', '0006_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidades',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='comunidades',
            name='tip_comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.comunidadesacademicas'),
        ),
    ]
