# Generated by Django 5.1.1 on 2024-12-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0004_remove_comunidades_tipologia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidades',
            name='fuente',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
    ]
