# Generated by Django 3.2.19 on 2023-10-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Publicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'publicador',
                'verbose_name_plural': 'publicadores',
                'db_table': 'publicador',
            },
        ),
        migrations.CreateModel(
            name='ConjuntoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.categoria')),
                ('publicadores', models.ManyToManyField(to='Modelos.Publicadores')),
            ],
            options={
                'verbose_name': 'conjunto_dato',
                'verbose_name_plural': 'conjunto_datos',
                'db_table': 'conjunto_dato',
            },
        ),
    ]
