# Generated by Django 3.2.19 on 2023-10-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_alter_publicadores_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
