# Generated by Django 3.2.19 on 2023-10-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_auto_20231030_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicadores',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/publicadores'),
        ),
        migrations.AddField(
            model_name='publicadores',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion'),
        ),
    ]
