# Generated by Django 3.2.19 on 2023-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_remove_publicadores_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicadores',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='publicadores',
            name='face',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='face'),
        ),
        migrations.AddField(
            model_name='publicadores',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='telefono'),
        ),
        migrations.AddField(
            model_name='publicadores',
            name='web',
            field=models.TextField(blank=True, null=True, verbose_name='web'),
        ),
        migrations.AlterField(
            model_name='publicadores',
            name='nombre',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='nombre'),
        ),
    ]
