# Generated by Django 3.2.19 on 2023-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0007_auto_20231031_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjuntodatos',
            name='documentos',
        ),
        migrations.AddField(
            model_name='conjuntodatos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion'),
        ),
    ]
