# Generated by Django 3.2.19 on 2023-11-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0008_auto_20231104_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntodatos',
            name='titulo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='titulo'),
        ),
    ]
