# Generated by Django 3.2.19 on 2023-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0009_conjuntodatos_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion')),
                ('titulo', models.CharField(max_length=250, verbose_name='titulo')),
                ('icon_text', models.CharField(max_length=250, verbose_name='titulo')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
