# Generated by Django 3.2.19 on 2023-11-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0010_proyectos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='titulo'),
        ),
    ]
