# Generated by Django 3.2.19 on 2023-11-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0011_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=250, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(verbose_name='descripcion'),
        ),
    ]
