# Generated by Django 3.2.19 on 2023-11-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0012_auto_20231108_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=115, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='icon_text',
            field=models.CharField(max_length=250, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.FileField(blank=True, null=True, upload_to='media/documentos')),
                ('cjtodatos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modelos.conjuntodatos')),
            ],
            options={
                'verbose_name': 'dato',
                'verbose_name_plural': 'datos',
                'db_table': 'dato',
            },
        ),
    ]
