# Generated by Django 3.2.19 on 2024-01-07 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Modelos', '0016_alter_historicalcategoria_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConjuntoDatos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='descripcion')),
                ('titulo', models.CharField(blank=True, max_length=250, null=True, verbose_name='titulo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Modelos.categoria')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_de_cjtodatos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical conjunto_dato',
                'verbose_name_plural': 'historical conjunto_datos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
