# Generated by Django 3.2.19 on 2024-06-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0018_auto_20240601_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='sigla',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sigla'),
        ),
    ]
