# Generated by Django 3.2.19 on 2024-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0019_auto_20240601_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=500, verbose_name='Municipio')),
                ('sigla', models.CharField(blank=True, max_length=25, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'db_table': 'municipio',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=500, verbose_name='Provincia')),
                ('sigla', models.CharField(blank=True, max_length=25, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
            },
        ),
    ]
