# Generated by Django 3.2.19 on 2024-06-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0020_municipio_provincia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.IntegerField(choices=[('1', 'Nacional'), ('2', 'Internacional'), ('3', 'Seleccione')])),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoría')),
                ('imagen', models.CharField(blank=True, max_length=250, null=True, verbose_name='Foto')),
                ('entidad', models.CharField(blank=True, max_length=500, null=True, verbose_name='Entidad Responsable')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='Región')),
                ('fuente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Año')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('descriptor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptores')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.municipio')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.pais')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.provincia')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
