# Generated by Django 3.2.19 on 2024-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0022_ordenamientoj'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratadosI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('tipologia', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tipología')),
                ('categoria', models.CharField(blank=True, max_length=500, null=True, verbose_name='Categoría')),
                ('organismo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Organismo Internacional')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fecha de emisión')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='media/documentos')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='media/images')),
                ('concepto', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Categoría Conceptual')),
            ],
            options={
                'verbose_name': 'tratado',
                'verbose_name_plural': 'tratados',
                'db_table': 'tratado',
            },
        ),
        migrations.AlterModelOptions(
            name='ordenamientoj',
            options={'verbose_name': 'ordenamiento', 'verbose_name_plural': 'ordenamientos'},
        ),
    ]
