# Generated by Django 3.2.19 on 2024-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0023_auto_20240602_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='bandera',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
