# Generated by Django 3.2.19 on 2024-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0024_alter_pais_bandera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='bandera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
