# Generated by Django 3.2.19 on 2024-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0026_auto_20240603_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='bandera_url',
        ),
        migrations.AddField(
            model_name='pais',
            name='bandera_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='bandera',
            field=models.URLField(blank=True, null=True),
        ),
    ]
