# Generated by Django 5.1.1 on 2024-11-13 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0002_afiliacion_cobertura_comunidadesacademicas_tematica_and_more'),
        ('Ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenamientoj',
            name='categoria',
        ),
        migrations.AddField(
            model_name='ordenamientoj',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.tematica'),
        ),
        migrations.AlterField(
            model_name='ordenamientoj',
            name='tipologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.tipologia'),
        ),
    ]
