# Generated by Django 5.1.1 on 2024-12-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenamiento', '0003_alter_ordenamientoj_tipologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('concepto', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Concepto')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordenamientoj',
            name='concepto',
        ),
        migrations.AddField(
            model_name='ordenamientoj',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ordenamiento.articulo'),
        ),
    ]
