# Generated by Django 5.1.1 on 2024-12-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenamiento', '0004_articulo_remove_ordenamientoj_concepto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenamientoj',
            name='tematica',
        ),
    ]
