# Generated by Django 5.1.1 on 2024-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenamiento', '0005_remove_ordenamientoj_tematica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenamientoj',
            name='articulo',
        ),
        migrations.AddField(
            model_name='ordenamientoj',
            name='articulos',
            field=models.ManyToManyField(blank=True, to='Ordenamiento.articulo'),
        ),
    ]
