# Generated by Django 5.1.1 on 2024-11-28 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomencladores', '0006_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('Libro', 'Libro'), ('Articulo', 'Articulo'), ('Tesis', 'Tesis'), ('Manual', 'Manual'), ('Audiovisual', 'Audiovisual'), ('Canal', 'Canal')])),
                ('programa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Programa')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('capitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Capítulo/Número')),
                ('enlace', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace')),
                ('fuente', models.CharField(blank=True, max_length=500, null=True, verbose_name='Fuente')),
                ('medio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Medio')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Año')),
                ('descriptores', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptores')),
                ('autores', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Autores')),
                ('editorial', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Editorial')),
                ('nombre_revista', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Nombre Revista')),
                ('no_edic', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Número de la edición')),
                ('resumen_art', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Resumen del artículo')),
                ('universidad', models.CharField(blank=True, max_length=10000, null=True, verbose_name='Universidad')),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.clasificacion')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.pais')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.region')),
                ('tematica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomencladores.tematica')),
            ],
            options={
                'verbose_name': 'resurso',
                'verbose_name_plural': 'recursos',
                'db_table': 'recurso',
            },
        ),
    ]
