# Generated by Django 5.1.1 on 2024-10-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del país.', max_length=500, verbose_name='País')),
                ('sigla', models.CharField(blank=True, help_text='Ingrese las siglas que identifican el país.', max_length=25, null=True, verbose_name='Sigla')),
                ('bandera', models.URLField(blank=True, help_text='Ingrese la url donde se encuentra la bandera del país', null=True)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'pais',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=500, verbose_name='Provincia')),
                ('sigla', models.CharField(blank=True, max_length=25, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'provincia',
                'verbose_name_plural': 'provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='RecursosA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Programa')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('capitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Capíyulo/Número')),
                ('enlace', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enlace')),
                ('medio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Medio')),
                ('year', models.CharField(blank=True, max_length=500, null=True, verbose_name='Año')),
                ('descriptores', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptores')),
                ('pais', models.CharField(blank=True, max_length=500, null=True, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=500, null=True, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'resurso',
                'verbose_name_plural': 'recursos',
                'db_table': 'recurso',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=500, verbose_name='Municipio')),
                ('sigla', models.CharField(blank=True, max_length=25, null=True, verbose_name='Sigla')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nomencladores.provincia')),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
                'db_table': 'municipio',
            },
        ),
    ]
