# Generated by Django 5.1.1 on 2024-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0002_afiliacion_cobertura_comunidadesacademicas_tematica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologia',
            name='nombre',
            field=models.CharField(help_text='Ingrese la tipología', max_length=500, verbose_name='Tipologías'),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='sigla',
            field=models.CharField(blank=True, help_text='Ingrese las siglas que identifican la tipología', max_length=25, null=True, verbose_name='Sigla'),
        ),
    ]
