# Generated by Django 5.1.1 on 2024-11-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0004_alter_tipologia_sigla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasif', models.CharField(help_text='Ingrese la clasificación', max_length=500, verbose_name='Clasificación')),
                ('sigla', models.CharField(blank=True, help_text='Ingrese las siglas que identifican la clasificación', max_length=25, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'clasificacion',
                'verbose_name_plural': 'clasificaciones',
                'db_table': 'clasificacion',
            },
        ),
        migrations.DeleteModel(
            name='RecursosA',
        ),
    ]
