# Generated by Django 5.1.1 on 2024-11-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomencladores', '0005_clasificacion_delete_recursosa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Ingrese la región', max_length=500, verbose_name='Región')),
                ('sigla', models.CharField(blank=True, help_text='Ingrese las siglas que identifican la región', max_length=25, null=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regiones',
                'db_table': 'region',
            },
        ),
    ]
